import { OrganigramaNodo } from '../../types/project';

export const ESTRUCTURAS_ORGANIGRAMA = [
  {
    id: 'funcional-procesos',
    nombre: 'Estructura Funcional por Procesos',
    descripcion: 'Agrupa las actividades según funciones especializadas (Producción, Comercial, Finanzas, I+D). Recomendada para pymes y empresas en crecimiento.',
  },
  {
    id: 'lineal-staff',
    nombre: 'Estructura Lineal y Staff',
    descripcion: 'Línea de mando directa con órganos consultivos de asesoría (Legal, Contable, Revisoría Fiscal) sin autoridad de mando directa.',
  },
  {
    id: 'matricial-proyectos',
    nombre: 'Estructura Matricial por Proyectos e Innovación',
    descripcion: 'Doble flujo de autoridad combinando departamentos funcionales con líderes de proyectos o líneas de producto.',
  },
  {
    id: 'divisional-productos',
    nombre: 'Estructura Divisional por Productos o Mercados',
    descripcion: 'Organizada en unidades autónomas según líneas de producto o regiones geográficas.',
  },
  {
    id: 'horizontal-agil',
    nombre: 'Estructura Horizontal / Ágil',
    descripcion: 'Pocos niveles jerárquicos intermedios, empoderamiento de equipos autónomos y toma de decisiones descentralizada.',
  },
];

export const DEFAULT_ORGANIGRAMA_NODOS: OrganigramaNodo[] = [
  {
    id: 'org-1',
    cargo: 'Junta de Socios / Asamblea General',
    nombre: 'Socios Fundadores',
    area: 'Alta Dirección',
    tipo: 'directivo',
    parentId: null,
    color: '#003366',
  },
  {
    id: 'org-2',
    cargo: 'Gerente General y Representante Legal',
    nombre: 'Gerencia General',
    area: 'Dirección General',
    tipo: 'directivo',
    parentId: 'org-1',
    color: '#1d4ed8',
  },
  {
    id: 'org-staff',
    cargo: 'Revisoría Fiscal y Contador Externo',
    nombre: 'Asesoría Contable',
    area: 'Staff / Asesoría',
    tipo: 'staff',
    parentId: 'org-2',
    color: '#475569',
  },
  {
    id: 'org-3',
    cargo: 'Director de Operaciones y Calidad',
    nombre: 'Dirección Operativa',
    area: 'Producción y Planta',
    tipo: 'departamento',
    parentId: 'org-2',
    color: '#059669',
  },
  {
    id: 'org-4',
    cargo: 'Ejecutivo de Ventas y Cuentas Clave',
    nombre: 'Área Comercial',
    area: 'Comercial y Marketing',
    tipo: 'departamento',
    parentId: 'org-2',
    color: '#d97706',
  },
  {
    id: 'org-5',
    cargo: 'Coordinador de Sostenibilidad e I+D',
    nombre: 'Innovación',
    area: 'Desarrollo de Producto',
    tipo: 'departamento',
    parentId: 'org-2',
    color: '#7c3aed',
  },
  {
    id: 'org-6',
    cargo: 'Técnico Operario de Producción 1',
    nombre: 'Operaciones',
    area: 'Planta de Producción',
    tipo: 'operativo',
    parentId: 'org-3',
    color: '#0d9488',
  },
  {
    id: 'org-7',
    cargo: 'Técnico Operario de Producción 2',
    nombre: 'Operaciones',
    area: 'Planta de Producción',
    tipo: 'operativo',
    parentId: 'org-3',
    color: '#0d9488',
  },
];

export const ORGANIGRAMA_PRESETS: {
  id: string;
  nombre: string;
  descripcion: string;
  tipoEstructura: string;
  nodos: OrganigramaNodo[];
}[] = [
  {
    id: 'preset-funcional',
    nombre: 'Plantilla Pyme Funcional (Recomendada CUN)',
    descripcion: 'Dirección General con áreas de Operaciones, Ventas e I+D con operarios.',
    tipoEstructura: 'Estructura Funcional por Procesos',
    nodos: DEFAULT_ORGANIGRAMA_NODOS,
  },
  {
    id: 'preset-startup',
    nombre: 'Plantilla Startup Ágil / Tecnológica',
    descripcion: 'Estructura horizontal con CEO, CTO, CPO, Asesor Legal y Desarrolladores.',
    tipoEstructura: 'Estructura Horizontal / Ágil',
    nodos: [
      {
        id: 'st-1',
        cargo: 'CEO / Co-Fundador',
        nombre: 'Liderazgo Ejecutivo',
        area: 'Dirección Estratégica',
        tipo: 'directivo',
        parentId: null,
        color: '#1e40af',
      },
      {
        id: 'st-staff',
        cargo: 'Asesor Legal & Propiedad Intelectual',
        nombre: 'Staff Consultor',
        area: 'Asesoría Externa',
        tipo: 'staff',
        parentId: 'st-1',
        color: '#475569',
      },
      {
        id: 'st-2',
        cargo: 'CTO / Director de Tecnología',
        nombre: 'Líder Técnico',
        area: 'Tecnología & Producto',
        tipo: 'departamento',
        parentId: 'st-1',
        color: '#059669',
      },
      {
        id: 'st-3',
        cargo: 'Head of Growth & Ventas',
        nombre: 'Líder Comercial',
        area: 'Marketing Digital & Ventas',
        tipo: 'departamento',
        parentId: 'st-1',
        color: '#d97706',
      },
      {
        id: 'st-4',
        cargo: 'Desarrollador Full Stack',
        nombre: 'Desarrollo',
        area: 'Ingeniería de Software',
        tipo: 'operativo',
        parentId: 'st-2',
        color: '#0284c7',
      },
      {
        id: 'st-5',
        cargo: 'Especialista de Experiencia (UX/UI)',
        nombre: 'Diseño',
        area: 'Diseño de Producto',
        tipo: 'operativo',
        parentId: 'st-2',
        color: '#9333ea',
      },
      {
        id: 'st-6',
        cargo: 'Especialista en Medios y Contenidos',
        nombre: 'Marketing',
        area: 'Adquisición de Clientes',
        tipo: 'operativo',
        parentId: 'st-3',
        color: '#e11d48',
      },
    ],
  },
  {
    id: 'preset-servicios',
    nombre: 'Plantilla Empresa de Servicios y Consultoría',
    descripcion: 'Enfocada en atención a clientes, gestión de proyectos y calidad de servicio.',
    tipoEstructura: 'Estructura Lineal y Staff',
    nodos: [
      {
        id: 'srv-1',
        cargo: 'Junta de Socios',
        nombre: 'Directorio',
        area: 'Alta Dirección',
        tipo: 'directivo',
        parentId: null,
        color: '#0f172a',
      },
      {
        id: 'srv-2',
        cargo: 'Director Ejecutivo (CEO)',
        nombre: 'Gerencia General',
        area: 'Administración y Dirección',
        tipo: 'directivo',
        parentId: 'srv-1',
        color: '#1d4ed8',
      },
      {
        id: 'srv-staff',
        cargo: 'Revisora Fiscal',
        nombre: 'Auditoría',
        area: 'Control y Vigilancia',
        tipo: 'staff',
        parentId: 'srv-2',
        color: '#64748b',
      },
      {
        id: 'srv-3',
        cargo: 'Líder de Proyectos y Operaciones',
        nombre: 'Operaciones',
        area: 'Prestación de Servicios',
        tipo: 'departamento',
        parentId: 'srv-2',
        color: '#0891b2',
      },
      {
        id: 'srv-4',
        cargo: 'Coordinador Administrativo y Financiero',
        nombre: 'Finanzas',
        area: 'Administración',
        tipo: 'departamento',
        parentId: 'srv-2',
        color: '#059669',
      },
      {
        id: 'srv-5',
        cargo: 'Consultor Senior / Especialista',
        nombre: 'Consultoría',
        area: 'Ejecución de Servicios',
        tipo: 'operativo',
        parentId: 'srv-3',
        color: '#4f46e5',
      },
      {
        id: 'srv-6',
        cargo: 'Asistente de Cuentas y Soporte al Cliente',
        nombre: 'Servicio al Cliente',
        area: 'Postventa y Soporte',
        tipo: 'operativo',
        parentId: 'srv-3',
        color: '#ea580c',
      },
    ],
  },
];
